package com.example.demo.ws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-03-21T15:43:43.433+08:00
 * Generated source version: 3.2.2
 *
 */
@WebService(targetNamespace = "http://service.ws.demo.example.com/", name = "HelloWorld")
public interface HelloWorld {

    @WebMethod
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://service.ws.demo.example.com/", className = "com.example.demo.ws.service.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://service.ws.demo.example.com/", className = "com.example.demo.ws.service.SayHiResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String sayHi(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "currentDate", targetNamespace = "http://service.ws.demo.example.com/", className = "com.example.demo.ws.service.CurrentDate")
    @ResponseWrapper(localName = "currentDateResponse", targetNamespace = "http://service.ws.demo.example.com/", className = "com.example.demo.ws.service.CurrentDateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public javax.xml.datatype.XMLGregorianCalendar currentDate();
}
